# Generated by Django 4.2.3 on 2023-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
