# Generated by Django 4.2.3 on 2023-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0002_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="private_key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="public_key",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
