# Generated by Django 4.2.3 on 2023-11-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0006_remove_user_private_key_remove_user_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
