# Generated by Django 4.2.3 on 2023-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0007_alter_user_address_alter_user_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_balance",
            field=models.DecimalField(
                decimal_places=2, default="0.99", max_digits=9999999999
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_coins",
            field=models.IntegerField(default="0"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_invested",
            field=models.DecimalField(
                decimal_places=2, default="0.99", max_digits=9999999999
            ),
        ),
    ]
