# Generated by Django 4.2.3 on 2023-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_user_total_balance_user_total_coins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="total_balance",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=9999999999
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="total_invested",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=9999999999
            ),
        ),
    ]
