# Generated by Django 4.2.3 on 2023-11-11 13:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0009_alter_user_total_balance_alter_user_total_invested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=django_countries.fields.CountryField(
                blank=True, default=1, max_length=2
            ),
            preserve_default=False,
        ),
    ]
