# Generated by Django 4.2.3 on 2023-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0010_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
