# Generated by Django 4.2.3 on 2023-11-12 19:39

import crypto_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="cat",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="category")),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="UserPaymentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Bitcoin", max_length=100)),
                ("initial", models.CharField(default="BTC", max_length=7)),
                (
                    "invested_amount",
                    models.DecimalField(
                        decimal_places=2, default="0", max_digits=99999
                    ),
                ),
                (
                    "invested_return",
                    models.DecimalField(
                        decimal_places=2, default="0", max_digits=99999
                    ),
                ),
                ("payment_status", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default="0", max_digits=999),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="cat",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Bitcoin", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("initial", models.CharField(default="BTC", max_length=7)),
                (
                    "image",
                    models.ImageField(
                        default="product.jpg",
                        upload_to=crypto_app.models.user_directory_path,
                    ),
                ),
                (
                    "invested_amount",
                    models.DecimalField(
                        decimal_places=2, default="0.99", max_digits=99999
                    ),
                ),
                (
                    "invested_return",
                    models.DecimalField(
                        decimal_places=2, default="1.99", max_digits=99999
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default="normal", max_length=100, null=True
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not processed", "Not Processed"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                        ],
                        default="in_review",
                        max_length=16,
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=10,
                        max_length=20,
                        prefix="plan",
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("rejected", "Rejected"),
                            ("in_review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="in_review",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="crypto_app.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Coins",
            },
        ),
    ]
