# Generated by Django 4.2.3 on 2023-10-28 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not processed", "Not Processed"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                        ],
                        default="not processing",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=50, null=True, unique=True)),
                ("last_name", models.CharField(max_length=50, null=True, unique=True)),
                ("phone", models.CharField(max_length=20, null=True, unique=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("private_key", models.CharField(max_length=500)),
                ("public_key", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
