# Generated by Django 4.2.3 on 2023-10-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="address",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
