# Generated by Django 4.2.3 on 2023-11-02 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0002_detail_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Detail",
        ),
    ]
