# Generated by Django 4.2.3 on 2023-11-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
