# Generated by Django 4.2.3 on 2023-11-05 12:35

import crypto_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0006_alter_coin_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="image",
            field=models.ImageField(
                default="product.jpg", upload_to=crypto_app.models.user_directory_path
            ),
        ),
    ]
