# Generated by Django 4.2.3 on 2023-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0008_category_coin_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="initial",
            field=models.CharField(default="BTC", max_length=7),
        ),
    ]
