# Generated by Django 4.2.3 on 2023-11-06 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0009_coin_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coin",
            options={"verbose_name_plural": "Coins"},
        ),
    ]
