# Generated by Django 4.2.3 on 2023-11-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0010_alter_coin_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPaymentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(default="Bitcoin", max_length=100)),
                ("initial", models.CharField(default="BTC", max_length=7)),
                (
                    "invested_amount",
                    models.DecimalField(
                        decimal_places=2, default="0", max_digits=9999999999
                    ),
                ),
                (
                    "invested_return",
                    models.DecimalField(
                        decimal_places=2, default="0", max_digits=9999999999
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not processed", "Not Processed"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                        ],
                        default="not_processing",
                        max_length=16,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("rejected", "Rejected"),
                            ("in_review", "In Review"),
                            ("published", "Published"),
                        ],
                        default="in_review",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
