# Generated by Django 4.2.3 on 2023-11-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0011_userpaymentreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpaymentreview",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=999),
        ),
    ]
