# Generated by Django 4.2.3 on 2023-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0012_userpaymentreview_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
