# Generated by Django 4.2.3 on 2023-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_app", "0014_remove_userpaymentreview_product_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpaymentreview",
            name="invested_amount",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=99999),
        ),
        migrations.AlterField(
            model_name="userpaymentreview",
            name="invested_return",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=99999),
        ),
    ]
